springdoc:
  swagger-ui:
    path: "/swagger-ui.html"

api:
  fludland:
    host: localhost:8081
  fileservice:
    host: localhost:8083
  sso:
    host: localhost:8084
  user-service:
    host: localhost:8085