application:
  db-schema-name: fileservice


preliquibase:
  enabled: true
  sql-script-references: classpath:db/preliquibase/schema.sql

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=${application.db-schema-name}
    username: postgres
    password: 123456
    hikari:
      pool-name: Fileservice-Pool
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${application.db-schema-name}
        show_sql: true
        format_sql: true
    show-sql: on

  liquibase:
    change-log: classpath:dbchangelog-master.xml
  jackson:
    default-property-inclusion: non_null

server:
  port: 8083
  tomcat:
    max-http-form-post-size: 4096
    max-swallow-size: 4096