user-service:
  db-schema-name: userservice

preliquibase:
  enabled: true
  sql-script-references: classpath:preliquibase/schema.sql

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=${user-service.db-schema-name}
    username: postgres
    password: 123456
    hikari:
      pool-name: UserService-Pool
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${user-service.db-schema-name}

  liquibase:
    change-log: classpath:dbchangelog-master.xml

server:
  port: 8085
