sso:
  db-schema-name: fludland


preliquibase:
  enabled: true
  sql-script-references: classpath:db/preliquibase/schema.sql

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=${sso.db-schema-name}
    username: postgres
    password: 123456
    hikari:
      pool-name: Poolname-FLULAND
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${sso.db-schema-name}
    show-sql: on

  liquibase:
    change-log: classpath:dbchangelog-master.xml
  jackson:
    default-property-inclusion: non_null

server:
  port: 8082
